# Linux build tools with the unmodified OpenHarmony SDK headers and libraries.
# CMake uses its Linux ELF rules; the variant keeps runtime platform selection explicit.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_SYSTEM_VARIANT openharmony)
get_filename_component(OHOS_PORT_WORK "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
set(CMAKE_C_COMPILER "${OHOS_PORT_WORK}/ohos-clang")
set(CMAKE_CXX_COMPILER "${OHOS_PORT_WORK}/ohos-clang++")
set(CMAKE_ASM_COMPILER "${OHOS_PORT_WORK}/ohos-clang")
set(OHOS_CROSS_NDK "$ENV{OHOS_CROSS_NDK}")
if(NOT OHOS_CROSS_NDK)
    set(OHOS_CROSS_NDK "/tmp/oheco-dotnet-ndk-verified")
endif()
set(OHOS_DEP_PREFIX "$ENV{OHOS_DEP_PREFIX}")
if(NOT OHOS_DEP_PREFIX)
    set(OHOS_DEP_PREFIX "/tmp/oheco-dotnet-deps-verified/install")
endif()
set(CMAKE_SYSROOT "${OHOS_CROSS_NDK}/sysroot")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${OHOS_DEP_PREFIX}")
list(PREPEND CMAKE_PREFIX_PATH "${OHOS_DEP_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(OPENSSL_ROOT_DIR "${OHOS_DEP_PREFIX}")
set(ICU_ROOT "${OHOS_DEP_PREFIX}")
set(ENV{PKG_CONFIG_LIBDIR} "${OHOS_DEP_PREFIX}/lib/pkgconfig")
set(ENV{PKG_CONFIG_PATH} "")
# Installed ELF dependencies are shipped alongside each binary/library.
set(CMAKE_INSTALL_RPATH "$ORIGIN")
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
# This is a real device runner: each executable is signed and run on the host.
set(CMAKE_CROSSCOMPILING_EMULATOR "python3;${OHOS_PORT_WORK}/run-on-host.py")
